[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = huge_app.csv

lib_deps =
    mathieucarbou/ESPAsyncWebServer @ ^3.3.23
    bblanchon/ArduinoJson @ ^6.21.3
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit ADS1X15 @ ^2.5.0
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.11.0
    arduino-libraries/NTPClient @ ^3.2.1

build_flags = 
    -D CORE_DEBUG_LEVEL=1
